---
title: "Functions-tutorial"
author: "SK"
date: "2/13/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Work with some data in degree F

- convert to C

```{r}
airtemps <- c(65, 77, 32, 63, 0, -20)

airtemps_C1 <- (airtemps[1]-32)*5/9
airtemps_C2 <- (airtemps[2]-32)*5/9
airtemps_C3 <- (airtemps[3]-32)*5/9
airtemps_C4 <- (airtemps[4]-32)*5/9
airtemps_C5 <- (airtemps[5]-32)*5/9
airtemps_C6 <- (airtemps[6]-32)*5/9
airtemps_C <- (airtemps-32)*5/9
```

# Write a function to do that

```{r}
fahr_to_celsius <- function(fahr) { #fahr = 100 makes default value of F=100
  celsius <- (fahr - 32) * 5/9
  return(celsius) # if not specified the last value is returned
}

celsius_temp <- fahr_to_celsius(airtemps)
celsius_temp
```

# Write a function to convert C to F

```{r}
celsius_to_fahr <- function(celsius) {
  fahr <- celsius * 9/5 + 32
  return (fahr)
}
fahrtemps <- C2F(celsius_temp)
fahrtemps == airtemps
```

# Show how to document Functions
Need to use ROxygen package to have these in help document
```{r}
#' Converts numeric temperature data from degrees in Fahrenhiet to degree Celsius
#' 
#'@param fahr the value in Fahrenheit to be converted
#'@return the converted value in Celsius
fahr_to_celsius <- function(fahr) { 
  celsius <- (fahr - 32) * 5/9
  return(celsius) 
}
```

## source function (.R)
```{r}
source("convert.R")
F2C(airtemps)
```

## use my package
```{r}
library(SKtools)
environment_info("This is cool!")
```

