---
title: "Data Visualization"
author: "Sanghoon Kang"
date: "2/14/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Reformat the data for plotting

[Alaska Department of Fish and Game, Division of Commercial Fisheries. 2017. Daily salmon escapement counts from the OceanAK database, Alaska, 1921-2017. Knowledge Network for Biocomplexity. doi:10.5063/F1S46Q6M.](https://knb.ecoinformatics.org/view/doi:10.5063/F1S46Q6M)

```{r}
library(leaflet)
  library(dplyr)
  library(tidyr)
  library(ggplot2)
  library(DT)
```


```{r}
esc <- read.csv("https://knb.ecoinformatics.org/knb/d1/mn/v2/object/urn%3Auuid%3Af119a05b-bbe7-4aea-93c6-85434dcb1c5e", stringsAsFactors = F)

head(esc)
```

* calculate annual escapment by species and region
    + 'separate', 'group_by', 'summarize' using the 'sum' function
* filter for just pacific salmon (Sockeye, Chinook, Coho, Pink, Chum)

```{r}
annual_esc <-esc %>% 
  separate(sampleDate, into = c("Year", "Month", "Day"), sep = "-") %>% 
  mutate(Year = as.numeric(Year)) %>% 
  group_by(Year, Species, SASAP.Region) %>% 
  summarize(Count = sum(DailyCount)) %>% 
  filter(Species %in% c("Sockeye", "Chinook", "Coho", "Pink", "Chum"))

head(annual_esc)

```

# Generate some static plots

```{r}
ggplot(annual_esc, mapping = aes(x = Species, y = Count, fill = SASAP.Region)) +
#  scale_fill_brewer(palette = "Dark2") +
  geom_col() #data and mapping calls can be overridden here
```

```{r}
my_theme <- theme_test() +
  theme(legend.position = "bottom", legend.title = element_blank())
```

```{r}
ggplot(filter(annual_esc, SASAP.Region == "Kodiak"), mapping = aes(x = Year, y = Count, color = Species)) +
  geom_line() +
  geom_point() +
  ylab("Escapement (num of fish)") +
  xlab("Year") +
  ggtitle("Kodiak Salmon Escapement") +
  theme_test() +
  theme(plot.title = element_text(hjust = 0.5))+
  my_theme
#  theme(legend.position = "bottom", legend.title = element_blank())
```


# Generate an interative map